UPDATE game SET  u_reg=1 WHERE u_nreg="Rui Fonseca Pedro";
UPDATE game SET  u_reg=2 WHERE u_nreg="' Ilidio Cruz";
UPDATE game SET  u_reg=3 WHERE u_nreg="'João Martins";
UPDATE game SET  u_reg=4 WHERE u_nreg="'Luís Ferreira /MBP)";
UPDATE game SET  u_reg=5 WHERE u_nreg="'Miguel Mello do Rego";
UPDATE game SET  u_reg=6 WHERE u_nreg="'Nuno Kreye MBP";
UPDATE game SET  u_reg=7 WHERE u_nreg="'Rogério Luís <rogerioluis@netcabo.pt>";
UPDATE game SET  u_reg=8 WHERE u_nreg="Alexandre Mendes";
UPDATE game SET  u_reg=9 WHERE u_nreg="Alexandre MEndes BlogTenis";
UPDATE game SET  u_reg=10 WHERE u_nreg="ande cochel";
UPDATE game SET  u_reg=10 WHERE u_nreg="Andre Cochel";
UPDATE game SET  u_reg=11 WHERE u_nreg="Andrea MBP";
UPDATE game SET  u_reg=12 WHERE u_nreg="António Baião";
UPDATE game SET  u_reg=13 WHERE u_nreg="António Cebola";
UPDATE game SET  u_reg=14 WHERE u_nreg="antonio corte real";
UPDATE game SET  u_reg=14 WHERE u_nreg="António Corte Real";
UPDATE game SET  u_reg=14 WHERE u_nreg="António Corte real";
UPDATE game SET  u_reg=15 WHERE u_nreg="Carlos";
UPDATE game SET  u_reg=16 WHERE u_nreg="Carlos bettencur MBP";
UPDATE game SET  u_reg=17 WHERE u_nreg="Carlos Borges Sousa, carlosborgessousa@gmail.com, 918300037";
UPDATE game SET  u_reg=18 WHERE u_nreg="CArlos Silva";
UPDATE game SET  u_reg=18 WHERE u_nreg="Carlos Silva";
UPDATE game SET  u_reg=19 WHERE u_nreg="Dinis";
UPDATE game SET  u_reg=20 WHERE u_nreg="Énio Pestana";
UPDATE game SET  u_reg=20 WHERE u_nreg="Énio Pestana MBP";
UPDATE game SET  u_reg=21 WHERE u_nreg="Fábio Vitório";
UPDATE game SET  u_reg=22 WHERE u_nreg="Feliz Santos";
UPDATE game SET  u_reg=23 WHERE u_nreg="Fernando Filipe MBP (FerFil)";
UPDATE game SET  u_reg=24 WHERE u_nreg="Francisco Silba";
UPDATE game SET  u_reg=24 WHERE u_nreg="Francisco Silva";
UPDATE game SET  u_reg=24 WHERE u_nreg="francisco silva";
UPDATE game SET  u_reg=25 WHERE u_nreg="Francisco Vinagre";
UPDATE game SET  u_reg=26 WHERE u_nreg="Frank Bacour";
UPDATE game SET  u_reg=27 WHERE u_nreg="Helder Santos MBP";
UPDATE game SET  u_reg=28 WHERE u_nreg="Henrique Pinto";
UPDATE game SET  u_reg=29 WHERE u_nreg="Hugo do raquect de Alvalade";
UPDATE game SET  u_reg=30 WHERE u_nreg="Hugo Palma";
UPDATE game SET  u_reg=31 WHERE u_nreg="Isidro";
UPDATE game SET  u_reg=31 WHERE u_nreg="Isidro Correia";
UPDATE game SET  u_reg=32 WHERE u_nreg="João Antunes";
UPDATE game SET  u_reg=33 WHERE u_nreg="João Faria";
UPDATE game SET  u_reg=34 WHERE u_nreg="joao gomes";
UPDATE game SET  u_reg=34 WHERE u_nreg="João Gomes";
UPDATE game SET  u_reg=35 WHERE u_nreg="joao martins";
UPDATE game SET  u_reg=35 WHERE u_nreg="João Martins";
UPDATE game SET  u_reg=35 WHERE u_nreg="João MArtins";
UPDATE game SET  u_reg=35 WHERE u_nreg="joão martins";
UPDATE game SET  u_reg=36 WHERE u_nreg="João Menino";
UPDATE game SET  u_reg=37 WHERE u_nreg="João Pedro Borges (1986)";
UPDATE game SET  u_reg=38 WHERE u_nreg="João Pereira MBP";
UPDATE game SET  u_reg=39 WHERE u_nreg="João Pimenta";
UPDATE game SET  u_reg=40 WHERE u_nreg="joao ramires";
UPDATE game SET  u_reg=40 WHERE u_nreg="João Ramires CTPL";
UPDATE game SET  u_reg=41 WHERE u_nreg="João Ramos Silva/MBP";
UPDATE game SET  u_reg=42 WHERE u_nreg="joão silva";
UPDATE game SET  u_reg=43 WHERE u_nreg="Jorge Felix CTPL";
UPDATE game SET  u_reg=44 WHERE u_nreg="José Mascarenhas";
UPDATE game SET  u_reg=45 WHERE u_nreg="Leonel Martinho";
UPDATE game SET  u_reg=45 WHERE u_nreg="LEonel Martinho";
UPDATE game SET  u_reg=46 WHERE u_nreg="leopoldo";
UPDATE game SET  u_reg=47 WHERE u_nreg="luis correia";
UPDATE game SET  u_reg=47 WHERE u_nreg="Luís Correia MBP";
UPDATE game SET  u_reg=48 WHERE u_nreg="Luís Grazina";
UPDATE game SET  u_reg=49 WHERE u_nreg="Luís Henriques";
UPDATE game SET  u_reg=50 WHERE u_nreg="Luís Rodrigues CTPL (não é o gestor do online tennis blog)";
UPDATE game SET  u_reg=51 WHERE u_nreg="Luís Rodrigues online-tenis-blog";
UPDATE game SET  u_reg=52 WHERE u_nreg="Luísa Gouveia";
UPDATE game SET  u_reg=52 WHERE u_nreg="Luísa Gouveia (“Nini”, 1962, lic-4214, nr. 49 ITF)";
UPDATE game SET  u_reg=53 WHERE u_nreg="Manuel Mauricio";
UPDATE game SET  u_reg=94 WHERE u_nreg="MArco Miguel";
UPDATE game SET  u_reg=53 WHERE u_nreg="Mauricio";
UPDATE game SET  u_reg=54 WHERE u_nreg="Miguel Andrade CTPL";
UPDATE game SET  u_reg=55 WHERE u_nreg="Miguel Mello do Rego";
UPDATE game SET  u_reg=56 WHERE u_nreg="Miguel Morais";
UPDATE game SET  u_reg=57 WHERE u_nreg="Miguel Rego Mello";
UPDATE game SET  u_reg=58 WHERE u_nreg="NULL";
UPDATE game SET  u_reg=59 WHERE u_nreg="Nuno Borges MBP, 1977";
UPDATE game SET  u_reg=60 WHERE u_nreg="Nuno Cordeiro MBP";
UPDATE game SET  u_reg=70 WHERE u_nreg="Nuno Duarte / MBP";
UPDATE game SET  u_reg=71 WHERE u_nreg="Nuno Encarnação";
UPDATE game SET  u_reg=72 WHERE u_nreg="Nuno Golveia MBP";
UPDATE game SET  u_reg=73 WHERE u_nreg="Nuno Vassallo Kreye";
UPDATE game SET  u_reg=74 WHERE u_nreg="Paula Zoio";
UPDATE game SET  u_reg=74 WHERE u_nreg="Paula Zoio (1961, lic-65420, nr 3 nac. +50 anos)";
UPDATE game SET  u_reg=75 WHERE u_nreg="Paulino Ferreira";
UPDATE game SET  u_reg=76 WHERE u_nreg="Paulo Nogueira Santos";
UPDATE game SET  u_reg=77 WHERE u_nreg="Paulo Pinto da Luz";
UPDATE game SET  u_reg=78 WHERE u_nreg="Pedro Belo";
UPDATE game SET  u_reg=79 WHERE u_nreg="Pedro Folgado MBP";
UPDATE game SET  u_reg=80 WHERE u_nreg="Pedro Menezes MBP";
UPDATE game SET  u_reg=81 WHERE u_nreg="Pedro Vila REal";
UPDATE game SET  u_reg=82 WHERE u_nreg="ricardo marques";
UPDATE game SET  u_reg=83 WHERE u_nreg="Ricardo Medeiros";
UPDATE game SET  u_reg=84 WHERE u_nreg="ricardo pizzaro";
UPDATE game SET  u_reg=85 WHERE u_nreg="Rui Azeredo";
UPDATE game SET  u_reg=86 WHERE u_nreg="Rui Cardal";
UPDATE game SET  u_reg=87 WHERE u_nreg="Rui Florêncio";
UPDATE game SET  u_reg=88 WHERE u_nreg="Rui Meireles";
UPDATE game SET  u_reg=89 WHERE u_nreg="Rui Rito";
UPDATE game SET  u_reg=90 WHERE u_nreg="Rui Sanchez Silva MBP";
UPDATE game SET  u_reg=91 WHERE u_nreg="telmo nobrega";
UPDATE game SET  u_reg=46 WHERE u_nreg="Tiago Leopoldo ONTBlog";
UPDATE game SET  u_reg=92 WHERE u_nreg="Tiago Sousa Dias";
UPDATE game SET  u_reg=93 WHERE u_nreg="X MBP";
