CREATE TABLE IF NOT EXISTS `player ` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nome` varchar(100) DEFAULT NULL,
  `origem` varchar(100) DEFAULT NULL,
  `nasc_ano` int(4) DEFAULT NULL,
  `lic_FPT` int(5) DEFAULT NULL,
  PRIMARY KEY (`id`)
);
INSERT INTO `player2` (`id`, `nome`, `origem`, `nasc_ano`, `lic_FPT`) VALUES
(1, 'Rui Fonseca Pedro', NULL, NULL, NULL),
(2, 'Ilidio Cruz', NULL, NULL, NULL),
(3, 'João Martins', NULL, NULL, NULL),
(4, 'Luís Ferreira', NULL, NULL, NULL),
(5, 'Miguel Mello do Rego', NULL, NULL, NULL),
(6, 'Nuno Kreye', NULL, NULL, NULL),
(7, 'Rogério Luís', NULL, NULL, NULL),
(8, 'Alexandre Mendes', NULL, NULL, NULL),
(9, 'Alexandre MEndes', NULL, NULL, NULL),
(10, 'Andre Cochel', NULL, NULL, NULL),
(10, 'Andre Cochel', NULL, NULL, NULL),
(11, 'Andrea', NULL, NULL, NULL),
(12, 'António Baião', NULL, NULL, NULL),
(13, 'António Cebola', NULL, NULL, NULL),
(14, 'António Corte Real', NULL, NULL, NULL),
(14, 'António Corte Real', NULL, NULL, NULL),
(14, 'António Corte Real', NULL, NULL, NULL),
(15, 'Carlos', NULL, NULL, NULL),
(16, 'Carlos bettencur', NULL, NULL, NULL),
(17, 'Carlos Borges Sousa', NULL, NULL, NULL),
(18, 'Carlos Silva', NULL, NULL, NULL),
(18, 'Carlos Silva', NULL, NULL, NULL),
(19, 'Dinis', NULL, NULL, NULL),
(20, 'Énio Pestana', NULL, NULL, NULL),
(20, 'Énio Pestana', NULL, NULL, NULL),
(21, 'Fábio Vitório', NULL, NULL, NULL),
(22, 'Feliz Santos', NULL, NULL, NULL),
(23, 'Fernando Filipe', NULL, NULL, NULL),
(24, 'Francisco Silva', NULL, NULL, NULL),
(24, 'Francisco Silva', NULL, NULL, NULL),
(24, 'Francisco Silva', NULL, NULL, NULL),
(25, 'Francisco Vinagre', NULL, NULL, NULL),
(26, 'Frank Bacour', NULL, NULL, NULL),
(27, 'Helder Santos', NULL, NULL, NULL),
(28, 'Henrique Pinto', NULL, NULL, NULL),
(29, 'Hugo', 'raquect de Alvalade', NULL, NULL),
(30, 'Hugo Palma', NULL, NULL, NULL),
(31, 'Isidro Correia', NULL, NULL, NULL),
(31, 'Isidro Correia', NULL, NULL, NULL),
(32, 'João Antunes', NULL, NULL, NULL),
(33, 'João Faria', NULL, NULL, NULL),
(34, 'João Gomes', NULL, NULL, NULL),
(34, 'João Gomes', NULL, NULL, NULL),
(35, 'João Martins', NULL, NULL, NULL),
(35, 'João Martins', NULL, NULL, NULL),
(35, 'João Martins', NULL, NULL, NULL),
(35, 'João Martins', NULL, NULL, NULL),
(36, 'João Menino', NULL, NULL, NULL),
(37, 'João Pedro Borges', NULL, 1986, NULL),
(38, 'João Pereira', NULL, NULL, NULL),
(39, 'João Pimenta', NULL, NULL, NULL),
(40, 'João Ramires', NULL, NULL, NULL),
(40, 'João Ramires', NULL, NULL, NULL),
(41, 'João Ramos Silva', 'MBP', NULL, NULL),
(42, 'João Silva', 'FCCN', NULL, NULL),
(43, 'Jorge Felix', NULL, NULL, NULL),
(44, 'José Mascarenhas', NULL, NULL, NULL),
(45, 'Leonel Martinho', NULL, NULL, NULL),
(45, 'Leonel Martinho', NULL, NULL, NULL),
(46, 'Leopoldo', NULL, NULL, NULL),
(47, 'Luís Correia', NULL, NULL, NULL),
(47, 'Luís Correia', NULL, NULL, NULL),
(48, 'Luís Grazina', NULL, NULL, NULL),
(49, 'Luís Henriques', NULL, NULL, NULL),
(50, 'Luís Rodrigues', 'CTPL', NULL, NULL),
(51, 'Luís Rodrigues', NULL, NULL, NULL),
(52, 'Luísa Gouveia', NULL, 1962, 4214),
(52, 'Luísa Gouveia', NULL, 1962, 4214),
(53, 'Manuel Mauricio', NULL, NULL, NULL),
(54, 'MArco Miguel', NULL, NULL, NULL),
(53, 'Manuel Mauricio', NULL, NULL, NULL),
(54, 'Miguel Andrade', 'FCCN', NULL, NULL),
(55, 'Miguel Mello do Rego', NULL, NULL, NULL),
(56, 'Miguel Morais', NULL, NULL, NULL),
(57, 'Miguel Rego Mello', NULL, NULL, NULL),
(58, NULL, NULL, NULL, NULL),
(59, 'Nuno Borges', 'MBP', 1977, NULL),
(60, 'Nuno Cordeiro ', 'MBP', NULL, NULL),
(70, 'Nuno Duarte', 'MBP', NULL, NULL),
(71, 'Nuno Encarnação', NULL, NULL, NULL),
(72, 'Nuno Golveia ', 'MBP', NULL, NULL),
(73, 'Nuno Vassallo Kreye', NULL, NULL, NULL),
(74, 'Paula Zoio', NULL, 1961, 65420),
(74, 'Paula Zoio', NULL, 1961, 65420),
(75, 'Paulino Ferreira', NULL, NULL, NULL),
(76, 'Paulo Nogueira Santos', NULL, NULL, NULL),
(77, 'Paulo Pinto da Luz', NULL, NULL, NULL),
(78, 'Pedro Belo', NULL, NULL, NULL),
(79, 'Pedro Folgado', NULL, NULL, NULL),
(80, 'Pedro Menezes', 'MBP', NULL, NULL),
(81, 'Pedro Vila REal', NULL, NULL, NULL),
(82, 'ricardo marques', NULL, NULL, NULL),
(83, 'Ricardo Medeiros', NULL, NULL, NULL),
(84, 'ricardo pizzaro', NULL, NULL, NULL),
(85, 'Rui Azeredo', NULL, NULL, NULL),
(86, 'Rui Cardal', NULL, NULL, NULL),
(87, 'Rui Florêncio', NULL, NULL, NULL),
(88, 'Rui Meireles', NULL, NULL, NULL),
(89, 'Rui Rito', NULL, NULL, NULL),
(90, 'Rui Sanchez Silva', NULL, NULL, NULL),
(91, 'Telmo Nobrega', NULL, NULL, NULL),
(46, 'Leopoldo', NULL, NULL, NULL),
(92, 'Tiago Sousa Dias', NULL, NULL, NULL),
(93, NULL, NULL, NULL, NULL);


